FROM dunglas/frankenphp:php8.5-bookworm

WORKDIR /app

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader --no-interaction

RUN php artisan optimize

CMD ["frankenphp", "php-server", "-r", "public/"]