FROM dunglas/frankenphp:1-php8.5-bookworm

RUN cp "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
    && install-php-extensions zip

WORKDIR /app

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --no-progress \
    --no-scripts \
    --optimize-autoloader \
    --prefer-dist

COPY . .

RUN mkdir -p \
    storage/framework/cache \
    storage/framework/sessions \
    storage/framework/views \
    bootstrap/cache \
    && composer dump-autoload --no-dev --classmap-authoritative

RUN chown -R www-data:www-data /app/storage /app/bootstrap/cache

COPY Caddyfile /etc/frankenphp/Caddyfile

ENV PORT=80 

USER www-data

CMD ["frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile"]